language: node_js

node_js:
  - 10

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install:
  - yarn install --no-progress

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
        - yarn generate

notifications:
  email: false
